---
apiServer:
  certSANs:
    - {{ ansible_eth0.ipv4.address }}
apiVersion: kubeadm.k8s.io/v1beta2
controllerManager: {}
dns:
  type: ""
etcd: {}
kind: ClusterConfiguration
networking:
  podSubnet: 192.168.0.0/24
scheduler: {}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint: {}
nodeRegistration:
  ignorePreflightErrors:
  - NumCPU
  - SystemVerification
  taints: []
